version: '3.7'

services:
  script:
    build: .
    command: >
      bash -c "python ETL.py
      && python app.py
      "
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db1
    ports:
      - 5432:5432

volumes:
  postgres_data: